version: 1

disable_existing_loggers: False

# Formatters and handlers will be dynamically configured in Python
# to support rich console output and structured file logging

formatters:
  rich:
    format: "%(message)s"
  audit:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: rich.logging.RichHandler
    rich_tracebacks: true
    show_time: true
    show_path: false
    markup: true
    formatter: rich
  audit_file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/audit.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    formatter: audit

loggers:
  nalai:
    level: INFO
    handlers: [console]
    propagate: False
  nalai.audit:
    level: INFO
    handlers: [audit_file]
    propagate: False
  models:
    level: INFO
    handlers: [console]
    propagate: False
  config:
    level: INFO
    handlers: [console]
    propagate: False
  ddtrace.llmobs:
    level: WARNING
    handlers: [console]
    propagate: False
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False
  fastapi:
    level: INFO
    handlers: [console]
    propagate: False

root:
  level: INFO
  handlers: [console]